//
//  WatchlistWorker.swift
//  Cryptotracker
//
//  Created by Abai Abakirov on 11/24/18.
//  Copyright (c) 2018 makeuseof. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class WatchlistWorker {
  func fetchCurrencies(_ completion: @escaping([CRCoin]) -> Void) {
    DispatchQueue.global(qos: .background).async {
      let coins = DataStore.shared.loadWatchlist()!
      DispatchQueue.main.async {
        completion(coins)
      }
    }
  }
  
  func fetchWatchlist() -> [CRCoin]? {
    return DataStore.shared.loadWatchlist()
  }
  
  func fetchCoins() -> [CRCoin]? {
    return DataStore.shared.loadCoins()
  }
  
  func fetchFavorite() -> CRCoin? {
    return DataStore.shared.loadFavorite()
  }
}
