//
//  WatchlistModels.swift
//  Cryptotracker
//
//  Created by Abai Abakirov on 11/24/18.
//  Copyright (c) 2018 makeuseof. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Watchlist {
  // MARK: Use cases
  
  enum Something {
    // swiftlint:disable nesting
    struct Request {
      let field: CRCoin.OrderField
      let type: CRCoin.OrderType
    }
    struct Response {
      let currencies: [CRCoin]
    }
    struct ViewModel {
      let currencies: [CRCoin]
    }
  }
  
  enum Favorite {
    struct Response {
      let id: Int
      let symbol: String
    }
    struct ViewModel {
      let id: Int
      let symbol: String
    }
  }
}
