//
//  PostPreviewWorker.swift
//  Cryptotracker
//
//  Created by Abai Abakirov on 11/22/18.
//  Copyright (c) 2018 makeuseof. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class PostPreviewWorker {  
  func fetchPost(postID: Int, completion: @escaping(Post?) -> Void) {
    completion(DataStore.shared.loadPost(postID))
  }
  
  func changeFont(_ size: Float, completion: @escaping(Float) -> Void) {
    UserDefaults.standard.set(size, forKey: "font_size")
    completion(size)
  }
  
  func fetchFontSize(_ completion: @escaping(Float) -> Void) {
    let defaults = UserDefaults.standard
    let defaultFontSize: Float = 0
    if let size = defaults.value(forKey: "font_size") as? Float {
      completion(size)
      return
    }
    defaults.set(defaultFontSize, forKey: "font_size")
    completion(defaultFontSize)
  }
}
