//
//  PostPreviewInteractor.swift
//  Cryptotracker
//
//  Created by Abai Abakirov on 11/22/18.
//  Copyright (c) 2018 makeuseof. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol PostPreviewBusinessLogic {
  func doSomething(request: PostPreview.Something.Request)
}

protocol PostPreviewDataStore {
  //var name: String { get set }
}

class PostPreviewInteractor: PostPreviewBusinessLogic, PostPreviewDataStore {
  var presenter: PostPreviewPresentationLogic?
  var worker: PostPreviewWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: PostPreview.Something.Request) {
    worker = PostPreviewWorker()
    worker?.doSomeWork()
    
    let response = PostPreview.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
