//
//  PostPreviewInteractor.swift
//  Cryptotracker
//
//  Created by Abai Abakirov on 11/22/18.
//  Copyright (c) 2018 makeuseof. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol PostPreviewBusinessLogic {
  func fetchPost(request: PostPreview.LoadPost.Request)
  func changeFontSize(request: PostPreview.ChangeFontSize.Request)
}

protocol PostPreviewDataStore {
  //var name: String { get set }
}

class PostPreviewInteractor: PostPreviewBusinessLogic, PostPreviewDataStore {
  var presenter: PostPreviewPresentationLogic?
  var worker: PostPreviewWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func fetchPost(request: PostPreview.LoadPost.Request) {
    worker = PostPreviewWorker()
    worker?.fetchPost(postID: request.postID, completion: { post in
      guard let post = post else {
        return
      }
      
      self.worker?.fetchFontSize { fontSize in
        let response = PostPreview.LoadPost.Response(post: post, fontSize: fontSize)
        self.presenter?.presentPost(response: response)
      }
    })
  }
  
  func changeFontSize(request: PostPreview.ChangeFontSize.Request) {
    worker = PostPreviewWorker()
    worker?.changeFont(request.size, completion: { size in
      self.presenter?.setPostFontSize(response: PostPreview.ChangeFontSize.ViewModel(size: size))
    })
  }
}
