//
//  PostsWorker.swift
//  Cryptotracker
//
//  Created by Abai Abakirov on 11/19/18.
//  Copyright (c) 2018 makeuseof. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class PostsWorker {
  func fetchPosts(completion: @escaping (_ posts: [Post]) -> Void) {
    DispatchQueue.global(qos: .background).async {
      
      if let localPosts = DataStore.shared.loadPosts() {
        DispatchQueue.main.async {
          completion(localPosts)
        }
      }
      
      let postsNetworkManager = PostsNetworkManager()
      postsNetworkManager.fetchPosts(completion: { posts, error in
        
        if error != nil {
          print(error!)
          return
        }
        
        guard let postList = posts else {
          fatalError("no posts")
        }
        DataStore.shared.insertPosts(postList)
        DispatchQueue.main.async {
          completion(postList)
        }
      })
    }
  }
  
  func fetchNextPosts(date: String, completion: @escaping (_ posts: [Post]) -> Void) {
    DispatchQueue.global(qos: .background).async {
      let postsNetworkManager = PostsNetworkManager()
      postsNetworkManager.fetchNextPosts(date: date, completion: { posts, error in
        if error != nil {
          print(error!)
          DispatchQueue.main.async {
            completion([Post]())
          }
          return
        }
        
        guard let postList = posts else {
          fatalError("no posts")
        }
        
        DataStore.shared.insertPosts(postList)
        
        DispatchQueue.main.async {
          completion(postList)
        }
      })
    }
  }
}
