//
//  PostsWorker.swift
//  Cryptotracker
//
//  Created by Abai Abakirov on 11/19/18.
//  Copyright (c) 2018 makeuseof. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class PostsWorker {
  func fetchPosts(completion: @escaping (_ posts: [Post]?, _ error: CTError?) -> Void) {
    DispatchQueue.global(qos: .background).async {
      let postsNetworkManager = PostsNetworkManager()
      postsNetworkManager.fetchPosts(completion: { posts, error in
        if error != nil {
          DispatchQueue.main.async {
            completion(nil, .network)
          }
          return
        }
        
        if posts == nil {
          DispatchQueue.main.async {
            completion(nil, .noData)
          }
        }
        
        DispatchQueue.main.async {
          completion(posts, nil)
        }
      })
    }
  }
  
  func fetchNextPosts(date: String, completion: @escaping (_ posts: [Post]?, _ error: CTError?) -> Void) {
    DispatchQueue.global(qos: .background).async {
      let postsNetworkManager = PostsNetworkManager()
      postsNetworkManager.fetchNextPosts(date: date, completion: { posts, error in
        if error != nil {
          DispatchQueue.main.async {
            completion(nil, .network)
          }
          return
        }
        
        if posts == nil {
          DispatchQueue.main.async {
            completion(nil, .noData)
          }
        }
        
        DispatchQueue.main.async {
          completion(posts, nil)
        }
      })
    }
  }
}
