//
//  PostsRouter.swift
//  Cryptotracker
//
//  Created by Abai Abakirov on 11/19/18.
//  Copyright (c) 2018 makeuseof. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol PostsRoutingLogic {
  func navigateToPostPreview(source: PostsViewController, destination: PostPreviewViewController)
}

protocol PostsDataPassing {
  var dataStore: PostsDataStore? { get }
}

class PostsRouter: NSObject, PostsRoutingLogic, PostsDataPassing {
  weak var viewController: PostsViewController?
  var dataStore: PostsDataStore?
  
  // MARK: Routing
  
  //func routeToSomewhere(segue: UIStoryboardSegue?)
  //{
  //  if let segue = segue {
  //    let destinationVC = segue.destination as! SomewhereViewController
  //    var destinationDS = destinationVC.router!.dataStore!
  //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
  //  } else {
  //    let storyboard = UIStoryboard(name: "Main", bundle: nil)
  //    let destinationVC = storyboard.instantiateViewController(withIdentifier: "SomewhereViewController")
//  as! SomewhereViewController
  //    var destinationDS = destinationVC.router!.dataStore!
  //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
  //    navigateToSomewhere(source: viewController!, destination: destinationVC)
  //  }
  //}

  // MARK: Navigation
  
  func navigateToPostPreview(source: PostsViewController, destination: PostPreviewViewController) {
    source.navigationController?.pushViewController(destination, animated: true)
  }
  
  // MARK: Passing data
  
  //func passDataToSomewhere(source: PostsDataStore, destination: inout SomewhereDataStore)
  //{
  //  destination.name = source.name
  //}
}
