//
//  ConfigModels.swift
//  Cryptotracker
//
//  Created by Abai Abakirov on 3/13/19.
//  Copyright (c) 2019 makeuseof. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Config {
  // MARK: Use cases
  
  enum Something {
    struct Request {}
    struct Response {}
    struct ViewModel {}
  }
}
