//
//  ConfigWorker.swift
//  Cryptotracker
//
//  Created by Abai Abakirov on 3/13/19.
//  Copyright (c) 2019 makeuseof. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class ConfigWorker {
  func getConfig(_ success: @escaping (_ config: Bootstrap) -> Void, _ failure: @escaping (_ error: String) -> Void) {
    ConfigNetworkManager().getConfig { config, error in
      if let error = error {
        failure(error)
        return
      }
      
      if let config = config {
        success(config)
      } else {
        failure(NMError.noData.localizedDescription)
      }
    }
  }
}
