//
//  ConfigRouter.swift
//  Cryptotracker
//
//  Created by Abai Abakirov on 3/13/19.
//  Copyright (c) 2019 makeuseof. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol ConfigRoutingLogic {
  func routeToMainScreen(segue: UIStoryboardSegue?)
}

protocol ConfigDataPassing {
  var dataStore: ConfigDataStore? { get }
}

class ConfigRouter: NSObject, ConfigRoutingLogic, ConfigDataPassing {
  weak var viewController: ConfigViewController?
  var dataStore: ConfigDataStore?
  
  // MARK: Routing
  
  func routeToMainScreen(segue: UIStoryboardSegue?)
  {
    let destinationVC = MainTabBarController()
    navigateToSomewhere(source: viewController!, destination: destinationVC)
  }

  // MARK: Navigation
  
  func navigateToSomewhere(source: ConfigViewController, destination: UIViewController)
  {
    source.navigationController?.setViewControllers([destination], animated: true)
  }
}
