//
//  ConfigPresenter.swift
//  Cryptotracker
//
//  Created by Abai Abakirov on 3/13/19.
//  Copyright (c) 2019 makeuseof. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ConfigPresentationLogic {
  func presentMainScreen()
  func presentError(_ error: String)
}

class ConfigPresenter: ConfigPresentationLogic {
  weak var viewController: ConfigDisplayLogic?
  
  // MARK: Do something
  
  func presentMainScreen() {
    viewController?.displayMainScreen()
  }
  
  func presentError(_ error: String) {
    viewController?.displayError(error)
  }
}
