//
//  ConfigInteractor.swift
//  Cryptotracker
//
//  Created by Abai Abakirov on 3/13/19.
//  Copyright (c) 2019 makeuseof. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ConfigBusinessLogic {
  func viewDidLoad()
}

protocol ConfigDataStore {
  //var name: String { get set }
}

class ConfigInteractor: ConfigBusinessLogic, ConfigDataStore {
  var presenter: ConfigPresentationLogic?
  var worker: ConfigWorker?
  
  func viewDidLoad() {
    worker = ConfigWorker()
    worker?.getConfig ( { config in
      if config.servers.count >= 1 {
        Constants.coinsBaseURL = config.servers[0].trimmingCharacters(in: ["/"])
      }
      self.presenter?.presentMainScreen()
    }, { error in
      self.presenter?.presentError(error)
    })
  }
}
