//
//  CurrenciesWorker.swift
//  Cryptotracker
//
//  Created by Abai Abakirov on 11/17/18.
//  Copyright (c) 2018 makeuseof. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class CurrenciesWorker {  
  func fetchCurrencies(_ completion: @escaping ([Currency]) -> Void) {
    DispatchQueue.global(qos: .background).async {
      let networkManager = CurrenciesNetworkManager()
      networkManager.getCurrencies(completion: { currencies, error in
        if error != nil {
          print(error!)
        }
        
        guard let curs = currencies else {
          return
        }
        DispatchQueue.main.async {
          completion(curs)
        }
      })
    }
  }
}
