//
//  CurrenciesPresenter.swift
//  Cryptotracker
//
//  Created by Abai Abakirov on 11/17/18.
//  Copyright (c) 2018 makeuseof. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CurrenciesPresentationLogic {
  func presentCurrencies(response: Currencies.FetchCoins.Response)
  func presentNextCoins(response: Currencies.LoadNext.Response)
  func presentLoadAll()
}

class CurrenciesPresenter: CurrenciesPresentationLogic {
  weak var viewController: CurrenciesDisplayLogic?
  
  func presentCurrencies(response: Currencies.FetchCoins.Response) {
    let viewModel = Currencies.FetchCoins.ViewModel(currencies: response.currencies.data.coins)
    viewController?.displaySomething(viewModel: viewModel)
  }
  
  func presentNextCoins(response: Currencies.LoadNext.Response) {
    let viewModel = Currencies.LoadNext.ViewModel(coins: response.coin.data.coins)
    viewController?.displayNext(viewModel: viewModel)
  }
  
  func presentLoadAll() {
    viewController?.displayLoadAll()
  }
}
