//
//  CurrenciesModels.swift
//  Cryptotracker
//
//  Created by Abai Abakirov on 11/17/18.
//  Copyright (c) 2018 makeuseof. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Currencies {
  // MARK: Use cases

  enum FetchCoins {
    // swiftlint:disable nesting
    struct Request {
      let limit: Int
      let force: Bool
    }
    
    struct Response {
      let currencies: CRRoot<CRDataList>
    }
    
    struct ViewModel {
      let currencies: [CRCoin]
    }
  }
  
  enum LocalCoins {
    struct Response {
      let coins: [CRCoin]
      let lastUpd: String
    }
  }
  
  enum LoadNext {
    struct Request {
      let limit: Int
      let offset: Int
    }
    
    struct Response {
      let coin: CRRoot<CRDataList>
    }
    
    struct ViewModel {
      let coins: [CRCoin]
    }
  }
}
