//
//  CurrenciesRouter.swift
//  Cryptotracker
//
//  Created by Abai Abakirov on 11/17/18.
//  Copyright (c) 2018 makeuseof. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol CurrenciesRoutingLogic {
  //func routeToSomewhere(segue: UIStoryboardSegue?)
  func openDetails(currencyID: Int, currencySymbol: String)
}

protocol CurrenciesDataPassing {
  var dataStore: CurrenciesDataStore? { get }
}

class CurrenciesRouter: NSObject, CurrenciesRoutingLogic, CurrenciesDataPassing {
  weak var viewController: CurrenciesViewController?
  var dataStore: CurrenciesDataStore?

  // MARK: Navigation
  
  func openDetails(currencyID: Int, currencySymbol: String) {
    let detailsVC = CurrencyDetailsViewController(currencyID: currencyID, currencySymbol: currencySymbol)
    viewController?.navigationController?.pushViewController(detailsVC, animated: true)
  }
}
