//
//  CurrenciesPresenter.swift
//  Cryptotracker
//
//  Created by Abai Abakirov on 11/17/18.
//  Copyright (c) 2018 makeuseof. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CurrenciesPresentationLogic {
  func presentSort(_ field: CRCoin.OrderField, _ type: CRCoin.OrderType)
  func presentCurrencies(response: Currencies.FetchCoins.ViewModel)
  func presentError(_ error: CTError)
}

class CurrenciesPresenter: CurrenciesPresentationLogic {
  weak var viewController: CurrenciesDisplayLogic?
  
  func presentCurrencies(response: Currencies.FetchCoins.ViewModel) {
    let viewModel = Currencies.FetchCoins.ViewModel(currencies: response.currencies)
    viewController?.displayCoins(viewModel: viewModel)
  }
  
  func presentError(_ error: CTError) {
    viewController?.displayError(error.rawValue)
  }
  
  func presentSort(_ field: CRCoin.OrderField, _ type: CRCoin.OrderType) {
    viewController?.setSort(field, type)
  }
}
