//
//  CurrenciesPresenter.swift
//  Cryptotracker
//
//  Created by Abai Abakirov on 11/17/18.
//  Copyright (c) 2018 makeuseof. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CurrenciesPresentationLogic {
  func presentSort(_ sortable: Sortable)
  func presentCurrencies(response: Currencies.FetchCoins.ViewModel)
  func presentLocalCoins(response: Currencies.LocalCoins.Response)
  func presentError(_ error: CWError)
}

class CurrenciesPresenter: CurrenciesPresentationLogic {
  var viewController: CurrenciesDisplayLogic?
  
  func presentCurrencies(response: Currencies.FetchCoins.ViewModel) {
    let viewModel = Currencies.FetchCoins.ViewModel(currencies: response.currencies)
    viewController?.displayCoins(viewModel: viewModel)
  }
  
  func presentError(_ error: CWError) {
    viewController?.displayError(error.localizedDescription)
  }
  
  func presentSort(_ sortable: Sortable) {
    viewController?.setSort(sortable: sortable)
  }
  
  func presentLocalCoins(response: Currencies.LocalCoins.Response) {
    viewController?.displayLocalCoins(viewModel: response)
  }
}
