//
//  CurrenciesWorker.swift
//  Cryptotracker
//
//  Created by Abai Abakirov on 11/17/18.
//  Copyright (c) 2018 makeuseof. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class CurrenciesWorker {
  
  func fetchLocalCurrencies() -> [CRCoin]? {
    return DataStore.shared.loadCoins()
  }
  
  func fetchCurrencies(limit: Int, offset: Int, _ completion: @escaping (CRRoot<CRDataList>) -> Void) {
    DispatchQueue.global(qos: .background).async {
      let networkManager = CurrenciesNetworkManager()
      networkManager.getCurrencies { currencies, error in
        if error != nil {
          print(error!)
        }
        
        guard let curs = currencies else {
          return
        }
        
        DataStore.shared.insertCoins(curs.data.coins)
        
        DispatchQueue.main.async {
          completion(curs)
        }
      }
    }
  }
  
  func setFavorite(_ coin: CRCoin) {
    DataStore.shared.resetFavorite()
    DataStore.shared.fullUpdate(coin)
  }
}
