//
//  AddToWatchlistModels.swift
//  Cryptotracker
//
//  Created by Abai Abakirov on 2/12/19.
//  Copyright (c) 2019 makeuseof. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum AddToWatchlist {
  struct Coin {
    let id: Int
    let isWatchlist: Bool
    let name: String
    let symbol: String
    let icon: CRCoin.IconType?
    let iconUrl: String?
    
    func set(watchlist: Bool) -> Coin {
      return Coin(id: id, isWatchlist: watchlist, name: name, symbol: symbol, icon: icon, iconUrl: iconUrl)
    }
  }
  
  // MARK: Use cases
  
  enum Something {
    // swiftlint:disable nesting
    struct Request {
    }
    struct Response {
      let coins: [Coin]
    }
    struct ViewModel {
      let coins: [Coin]
    }
    
  }
  
  enum Add {
    struct Request {
      let id: Int
      let symbol: String
      let isWatchlist: Bool
      let position: Int
    }
    
    struct Response {
      let position: Int
      let isWatchlist: Bool
    }
    
    struct ViewModel {
      let position: Int
      let isWatchlist: Bool
    }
  }
}
