//
//  AddToWatchlistInteractor.swift
//  Cryptotracker
//
//  Created by Abai Abakirov on 2/12/19.
//  Copyright (c) 2019 makeuseof. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol AddToWatchlistBusinessLogic {
  func doSomething(request: AddToWatchlist.Something.Request)
  func addToWatchlist(id: AddToWatchlist.Add.Request)
}

protocol AddToWatchlistDataStore {
  //var name: String { get set }
}

class AddToWatchlistInteractor: AddToWatchlistBusinessLogic, AddToWatchlistDataStore {
  var presenter: AddToWatchlistPresentationLogic?
  var worker: AddToWatchlistWorker?

  func doSomething(request: AddToWatchlist.Something.Request) {
    worker = AddToWatchlistWorker()
    worker?.fetchCoins { currencies in
      if currencies == nil {
        self.presenter?.presentEmptyList()
      } else {
        let response = AddToWatchlist.Something.Response(coins: currencies!)
        self.presenter?.presentSomething(response: response)
      }
    }
  }
  
  func addToWatchlist(id: AddToWatchlist.Add.Request) {
    worker = AddToWatchlistWorker()
    worker?.addToWatchlist(id) { response in
      self.presenter?.addToWatchlist(response: response)
    }
  }
}
