//
//  AddToWatchlistWorker.swift
//  Cryptotracker
//
//  Created by Abai Abakirov on 2/12/19.
//  Copyright (c) 2019 makeuseof. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class AddToWatchlistWorker {
  func fetchCoins(_ completion: @escaping([CRCoin]?) -> Void) {
    DispatchQueue.global(qos: .background).async {
      let savedCurrency = DataStore.shared.loadCoins()
      DispatchQueue.main.async {
        completion(savedCurrency)
      }
    }
  }
  
  func addToWatchlist(_ input: AddToWatchlist.Add.Request,_ completion: @escaping(AddToWatchlist.Add.Response) -> Void) {
    var coin = input.coin
    coin.isWatchlist = !coin.isWatchlist
    DataStore.shared.fullUpdate(coin)
    completion(AddToWatchlist.Add.Response(position: input.position, coin: coin))
  }
}
