//
//  CurrencyDetailsPresenter.swift
//  Cryptotracker
//
//  Created by Abai Abakirov on 11/24/18.
//  Copyright (c) 2018 makeuseof. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CurrencyDetailsPresentationLogic {
  func presentCoinDetails(coin: CRCoin)
  func favorites(coin: CRCoin)
  func presentWebsite()
  func presentError(_ error: CWError)
}

class CurrencyDetailsPresenter: CurrencyDetailsPresentationLogic {
  typealias CurrencyInfo = DetailsModel.Info
  
  weak var viewController: DetailsDisplayLogic?
  var coinSite: URL?
  
  // MARK: Do something
  
  func presentCoinDetails(coin: CRCoin) {
    let currInfo = [CurrencyInfo(name: "Price:",
                                 value: coin.price?.long,
                                 valueColor: nil),
                    CurrencyInfo(name: "% Change:",
                                 value: coin.changeStr,
                                 valueColor: coin.changeColor),
                    CurrencyInfo(name: "Market Cap:",
                                 value: coin.marketCap?.long,
                                 valueColor: nil),
                    CurrencyInfo(name: "Volume 24h:",
                                 value: coin.volume?.long,
                                 valueColor: nil),
                    CurrencyInfo(name: "Available supply:",
                                 value: coin.circulatingSupply?.long,
                                 valueColor: nil),
                    CurrencyInfo(name: "Total supply:",
                                 value: coin.totalSupply?.long,
                                 valueColor: nil)]

    let viewModel = DetailsModel(iconType: coin.iconType,
                                 iconUrl: coin.iconUrl,
                                 title: "\(coin.name) \(coin.symbol)",
                                 saveCurrency: coin,
                                 info: currInfo)
    viewController?.displayDetails(details: viewModel)
    coinSite = coin.websiteUrl
  }
  
  func favorites(coin: CRCoin) {
    viewController?.changeFavorites(coin: coin)
  }
  
  func presentWebsite() {
    if coinSite != nil {
      viewController?.openCoinWebsite(site: coinSite!)
    } else {
      viewController?.openNoCoinWebsite()
    }
  }
  
  func presentError(_ error: CWError) {
    viewController?.displayError(error.localizedDescription)
  }
}
