//
//  CurrencyDetailsWorker.swift
//  Cryptotracker
//
//  Created by Abai Abakirov on 11/24/18.
//  Copyright (c) 2018 makeuseof. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class CurrencyDetailsWorker {
  func doSomeWork(currID: Int, _ completion: @escaping(Currency) -> Void) {
    DispatchQueue.global(qos: .background).async {
      let networkManager = CurrenciesNetworkManager()
      networkManager.getCurrency(currID: currID, { currency, error in
        guard let curr = currency else {
          fatalError()
        }
        
        DispatchQueue.main.async {
          completion(curr)
        }
      })
    }
  }
  
  func loadSaveCurrency(currID: Int) -> SaveCurrency? {
    return DataStore.shared.loadSaveCurrency(currID)
  }
  
  func addToFavorites(_ currency: SaveCurrency) {
    DataStore.shared.insertSaveCurrency(currency)
  }
}
