//
//  CurrencyDetailsModels.swift
//  Cryptotracker
//
//  Created by Abai Abakirov on 11/24/18.
//  Copyright (c) 2018 makeuseof. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum CurrencyDetails {
  // MARK: Use cases
  
  enum AddFavorite {
    struct Request {
      let coin: CRCoin
    }
    
    struct Response {
      let coin: CRCoin
    }
    
    struct ViewModel {
      let coin: CRCoin
    }
  }
  
  enum Something {
    // swiftlint:disable nesting
    struct Request {
      let currID: Int
    }
    struct Response {
      let coin: CRCoin
    }
    struct ViewModel {
      let title: String
      let saveCurrency: CRCoin?
      let info: [Info]
      struct Info {
        let name: String
        let value: String?
        let valueColor: UIColor?
      }
    }
  }
}
