//
//  CurrencyDetailsWorker.swift
//  Cryptotracker
//
//  Created by Abai Abakirov on 11/24/18.
//  Copyright (c) 2018 makeuseof. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class CurrencyDetailsWorker {
  func doSomeWork(currID: Int, _ completion: @escaping(CRCoin) -> Void) {
    DispatchQueue.global(qos: .background).async {
      let coin = DataStore.shared.fetchCoin(currID)!
      DispatchQueue.main.async {
        completion(coin)
      }
    }
  }
  
  func update(_ coin: CRCoin) {
    DataStore.shared.fullUpdate(coin)
  }
}
